var MODIFIER_GROUP_CONFIG = {
  SHEET_NAME: 'ModifierGroups',
  HEADER_ROW: CONFIG.HEADER_ROW,
  FIRST_DATA_ROW: CONFIG.FIRST_DATA_ROW,
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 200,
  COLUMNS: {
    id: 1,
    name: 2
  },
  TOTAL_COLUMNS: 2,
  HEADERS: [
    'ID',
    'Name'
  ]
};
